# This file was generated by taking the reference REF0015-g_mg_hybrid (
# Salmonella experiment, Illumina + PabBio)
# - checkm2, dram and gtdbtk come from annotating the entire dataset
# - the bins come from the dereplication at 95%
# - the count data comes from MSEB0015

# read the dereplicated bins
bins <- read_tsv("bins.tsv", col_names = c("bin_id")) |> pull(bin_id)

# read the entire checkm2 report and keep the 10 most complete and least
# contaminated bins
top10 <-
  read_tsv("checkm2.quality_report.tsv.xz") |>
  filter(Name %in% bins) |>
  arrange(desc(Completeness), Contamination) |>
  slice(1:10) |>
  pull(Name) |>
  sort()

# slice each annotation file
checkm2 <-
  read_tsv("checkm2.quality_report.tsv.xz") |>
  filter(Name %in% top10)

gtdbtk <-
  read_tsv("gtdbtk.summary.tsv.xz") |>
  filter(user_genome %in% top10)

dram <-
  read_tsv("dram.annotations.tsv.gz") |>
  filter(fasta %in% top10)

# Slice the count table to get the top10 bins and the first 10 samples
colnames <- c(
  "M301474.lib1", "M301475.lib1", "M301476.lib1", "M301477.lib1",
  "M301478.lib1", "M301479.lib1", "M301480.lib1", "M301481.lib1",
  "M301482.lib1", "M301483.lib1"
)

counts <-
  read_tsv("coverm_genome_REF0015-g_mg_hybrid.count.tsv.xz") |>
  filter(sequence_id %in% top10) |>
  select(sequence_id, all_of(colnames))

rm(bins, colnames, top10)

save(
  checkm2,
  file = "data/checkm2.rda",
  compress = "xz",
  compression_level = 9,
  version = 2
)

save(
  gtdbtk,
  file = "data/gtdbtk.rda",
  compress = "xz",
  compression_level = 9,
  version = 2
)

save(
  dram,
  file = "data/dram.rda",
  compress = "xz",
  compression_level = 9,
  version = 2
)

save(
  counts,
  file = "data/counts.rda",
  compress = "xz",
  compression_level = 9,
  version = 2
)
